# Global configuration
app:
  name: HomeGuard
  env: dev            # dev / prod / test

ai:
  openai:
    api_key: "${OPENAI_API_KEY}"   # Load from environment variable
    model: "gpt-4o-mini"

# Database configuration
database:
  default: &sqlite
    driver: sqlite+aiosqlite
    database: "./data/homeguard.db"
    echo: false
    pool_pre_ping: true

  dev: &dev_mysql
    driver: mysql+asyncmy
    host: 192.168.110.126
    port: 3306
    database: homeguard
    username: root
    password: "${DB_PASSWORD}"      # Load from environment variable
    echo: false
    pool_pre_ping: true

  prod: &prod_pg
    driver: postgresql+asyncpg
    host: 10.0.0.21
    port: 5432
    database: homeguard
    username: pguser
    password: "${DB_PASSWORD}"      # Load from environment variable
    echo: false
    pool_pre_ping: true

# Logging configuration
logging:
  root_level: INFO
  file_level: DEBUG
  console: true
  log_dir: "{system_tmp}/logs/{app_name}"